#!/usr/bin/env bash
set -euo pipefail

# Purpose: Run one-time imperative setup steps with confirmations and idempotent checks.
# Behavior: Elevates via sudo, runs server-only steps only on the server host, and
# warns if steps appear already done. Prompts for inputs only after confirmation.
# Steps covered: Tailscale auth, Samba password (server), and Playit claim (server).
# Secrets (like Cloudflare tokens) are now managed declaratively via sops-nix.

SERVER_HOST="nixos-server"
HOSTNAME_SHORT="$(hostname -s)"
IS_SERVER=0
[[ "$HOSTNAME_SHORT" == "$SERVER_HOST" ]] && IS_SERVER=1

# Re-exec with sudo so the remainder runs as root.
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  exec sudo -E "$0" "$@"
fi

SUDO_USER_REAL=${SUDO_USER:-${LOGNAME:-$(whoami)}}

info()  { printf "[INFO] %s\n" "$*"; }
warn()  { printf "[WARN] %s\n" "$*"; }
error() { printf "[ERROR] %s\n" "$*"; exit 1; }

confirm_step() {
  local desc="$1" already="$2"
  if [[ -n "$already" ]]; then
    warn "$already"
  fi
  read -r -p "Proceed with ${desc}? [y/N]: " resp
  [[ "$resp" =~ ^[Yy]$ ]]
}

step_tailscale() {
  # Ensure the host is logged into the tailnet with SSH enabled.
  local desc="Tailscale login (tailscale up --ssh)"
  local already=""
  if command -v tailscale >/dev/null 2>&1; then
    if tailscale status --peers=false >/dev/null 2>&1; then
      already="Tailscale already authenticated; skip unless you need to re-auth."
    fi
  else
    error "tailscale binary not found; ensure Tailscale is installed."
  fi
  if confirm_step "$desc" "$already"; then
    read -r -p "Enter Tailscale auth key (blank for interactive login): " AUTHKEY
    if [[ -n "$AUTHKEY" ]]; then
      tailscale up --ssh --authkey "$AUTHKEY"
    else
      tailscale up --ssh
    fi
  fi
}

step_samba_password() {
  # Server-only: set or update the Samba password for the invoking user.
  [[ $IS_SERVER -eq 1 ]] || { info "Skipping Samba password (not server host)."; return; }
  local user="$SUDO_USER_REAL"
  local desc="Set Samba password for user '$user'"
  local already=""
  if command -v pdbedit >/dev/null 2>&1; then
    if pdbedit -L 2>/dev/null | grep -q "^${user}:"; then
      already="Samba password already set for ${user}; skipping recommended."
    fi
  else
    warn "pdbedit not found; Samba may not be installed."
  fi
  if confirm_step "$desc" "$already"; then
    smbpasswd -a "$user"
  fi
}

step_playit_claim() {
  # Server-only: claim the Playit agent and place the secret where the service expects it.
  [[ $IS_SERVER -eq 1 ]] || { info "Skipping Playit claim (not server host)."; return; }
  local desc="Run playit agent claim (interactive)"
  local already=""
  if [[ -f /var/lib/playit/playit.toml ]]; then
    already="/var/lib/playit/playit.toml exists; claim likely done."
  fi
  if confirm_step "$desc" "$already"; then
    # Run as the invoking user so config lands in their home, then instruct copy.
    sudo -u "$SUDO_USER_REAL" nix run github:pedorich-n/playit-nixos-module#playit-cli -- start
    if [[ -f "/home/${SUDO_USER_REAL}/.config/playit_gg/playit.toml" ]]; then
      info "Copying claimed playit.toml into /var/lib/playit ..."
      install -d -m755 /var/lib/playit
      install -m600 "/home/${SUDO_USER_REAL}/.config/playit_gg/playit.toml" /var/lib/playit/playit.toml
      chown playit:playit /var/lib/playit/playit.toml
    else
      warn "Could not find ~/.config/playit_gg/playit.toml after claim; copy manually if created."
    fi
  fi
}

step_sops_setup() {
  # Server-only: configure sops-nix for secrets management
  [[ $IS_SERVER -eq 1 ]] || { info "Skipping sops setup (not server host)."; return; }
  local desc="Configure sops-nix secrets (get age key, update .sops.yaml, encrypt secrets)"
  local already=""
  local key_file="/var/lib/sops-nix/key.txt"
  
  if [[ ! -f "$key_file" ]]; then
    already="Age key not found at $key_file; will be generated on first nixos-rebuild."
  fi
  
  if confirm_step "$desc" "$already"; then
    # Ensure age key exists
    if [[ ! -f "$key_file" ]]; then
      info "Age key will be auto-generated by sops-nix on first nixos-rebuild."
      info "Run 'sudo nixos-rebuild switch' first, then re-run this script."
      return
    fi
    
    # Extract public key
    info "Extracting age public key from $key_file..."
    local pub_key
    pub_key=$(nix-shell -p age --run "age-keygen -y $key_file 2>/dev/null")
    
    if [[ -z "$pub_key" ]]; then
      error "Failed to extract age public key."
    fi
    
    info "Age public key: $pub_key"
    
    # Update .sops.yaml
    local sops_config="/home/${SUDO_USER_REAL}/nixos-config/.sops.yaml"
    if [[ -f "$sops_config" ]]; then
      info "Updating $sops_config with age public key..."
      sed -i "s|age1placeholder|$pub_key|" "$sops_config"
      chown "$SUDO_USER_REAL:users" "$sops_config"
    else
      warn ".sops.yaml not found; skipping update."
    fi
    
    # Prompt for secrets and encrypt
    info "Now you need to encrypt your secrets."
    read -r -p "Enter Cloudflare API token (DNS edit for lhsv.net): " CF_TOKEN
    read -r -p "Enter Samba password for auto-mounting: " -s SAMBA_PASSWORD
    echo ""
    
    if [[ -n "$CF_TOKEN" || -n "$SAMBA_PASSWORD" ]]; then
      local secrets_file="/home/${SUDO_USER_REAL}/nixos-config/secrets/secrets.yaml"
      info "Creating and encrypting $secrets_file..."
      
      # Create unencrypted secrets file temporarily
      cat > "$secrets_file" <<EOF
# Cloudflare API token for DNS-01 challenges (used by Caddy)
cloudflare-dns-token: CLOUDFLARE_API_TOKEN=$CF_TOKEN
# Samba credentials for auto-mounting server on clients
samba-credentials: |
  username=leyton
  password=$SAMBA_PASSWORD
  domain=WORKGROUP
EOF
      chown "$SUDO_USER_REAL:users" "$secrets_file"
      
      # Encrypt it with sops
      info "Encrypting secrets file..."
      cd "/home/${SUDO_USER_REAL}/nixos-config"
      export SOPS_AGE_KEY_FILE="$key_file"
      sudo -E nix-shell -p sops --run "sops -e -i $secrets_file"
      
      info "Secrets encrypted successfully!"
      info "Don't forget to: cd ~/nixos-config && git add .sops.yaml secrets/secrets.yaml && git commit"
    else
      warn "No secrets provided; skipping secrets encryption."
    fi
  fi
}

main() {
  info "Detected host: $HOSTNAME_SHORT (server=${IS_SERVER})"
  step_tailscale
  step_samba_password
  step_playit_claim
  step_sops_setup
  info "All selected steps completed."
}

main "$@"
