#!/usr/bin/env bash
# sops-nix Base Setup Step

get_sops_base_help() {
  echo "Configure age encryption for secrets management. Extracts your age key and updates .sops.yaml."
}

check_sops_base_status() {
  if [[ ! -f "$AGE_KEY_FILE" ]]; then
    echo "needed"
    return
  fi
  
  local pub_key
  pub_key=$(get_age_public_key "$AGE_KEY_FILE" 2>/dev/null)
  
  if [[ -n "$pub_key" ]] && grep -q "$pub_key" "$SOPS_CONFIG" 2>/dev/null; then
    echo "done"
  else
    echo "needed"
  fi
}

step_sops_base_setup() {
  info "Configuring sops-nix base setup..."
  
  # Check if age key exists, if not inform user
  if [[ ! -f "$AGE_KEY_FILE" ]]; then
    warn "Age key not found at $AGE_KEY_FILE"
    info "The age key is auto-generated by sops-nix on first nixos-rebuild"
    info "Please run 'sudo nixos-rebuild switch' first, then re-run this script"
    return 0
  fi
  
  if [[ "${STEP_STATUS[sops_base]}" == "done" ]]; then
    warn "sops already configured; updating anyway"
  fi
  
  # Extract and display public key
  info "Extracting age public key from $AGE_KEY_FILE..."
  local pub_key
  pub_key=$(get_age_public_key "$AGE_KEY_FILE")
  
  if [[ -z "$pub_key" ]]; then
    error "Failed to extract age public key"
  fi
  
  info "Age public key: $pub_key"
  
  # Update .sops.yaml
  update_sops_yaml "$pub_key"
  
  success "sops-nix base setup complete"
  info "Don't forget to commit: cd ~/nixos-config && git add .sops.yaml && git commit"
}
